name: Update Text Files

on:
  schedule:
    - cron: "0 0 */7 * *" # Chạy mỗi 7 ngày vào 00:00 UTC
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  update-text-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch text files from URLs
        run: |
          urls=(
            "https://easylist.to/easylist/easylist.txt"
            "https://easylist.to/easylist/easyprivacy.txt"
            "https://abpvn.com/filter/abpvn-bGPG26.txt"
            "https://secure.fanboy.co.nz/fanboy-cookiemonster.txt"
            "https://secure.fanboy.co.nz/fanboy-annoyance.txt"
            "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_18_Annoyances_Cookies/filter.txt"
            "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_19_Annoyances_Popups/filter.txt"
            "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_22_Annoyances_Widgets/filter.txt"
            
          )

          # Định nghĩa nhóm file
          output_files=("1.txt" "2.txt" "3.txt")

          # Xóa nội dung cũ nếu có
          > "${output_files[0]}"
          > "${output_files[1]}"
          > "${output_files[2]}"

          # Tải nội dung theo nhóm
          for i in "${!urls[@]}"; do
            if [ "$i" -lt 3 ]; then
              output="${output_files[0]}"
            elif [ "$i" -lt 5 ]; then
              output="${output_files[1]}"
            else
              output="${output_files[2]}"
            fi
            echo "Fetching: ${urls[$i]} -> $output"
            curl -s "${urls[$i]}" >> "$output"
            echo -e "\n" >> "$output" # Xuống dòng giữa các file
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add group1.txt group2.txt group3.txt
          git commit -m "Auto-update filter lists [skip ci]" || exit 0
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
